### ISSUE TITLE
[EPIC] Prepare Dofigen v2

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/dofigen#200]
## What should be done 
Prepare the new Dofigen version that will include API breaking changes.

Prepare CLI API changes:

- [x] The CLI can have subcommands in order to manage some additional tasks (ex: https://github.com/lenra-io/dofigen/issues/181)
- [x] The ignore file is not given anymore since it is defined based on the Dockefile file (https://github.com/lenra-io/dofigen/issues/195)

Prepare Lib and YAML API changes: 

- [x] Use Dockerfile commands as default attribute names
- [x] Make most of the attributes as explicit as possible by creating corresponding struct that implements FromString to be parsable as today (ex: https://github.com/lenra-io/dofigen/issues/136)

## Technical recommandation

Add many unit tests before changing anything and refactor the code to be more readable by refactoring the code using functional syntax.

- [x] https://github.com/lenra-io/dofigen/issues/199

## Ecological concerns

Use more ref instead of cloning struts.

## Is this task linked with any other ?

- [x] #193
- [x] #181
- [x] #180
- [x] #206
- [x] #212
- [x] #215
- [x] #219
- [x] #222
- [x] #224
